Section "Device"
    Identifier "SPECTER HDMI"
    Driver "modesetting"
    Option "kmsdev" "/dev/dri/card1"
EndSection

Section "Screen"
    Identifier "SPECTER Screen"
    Device "SPECTER HDMI"
EndSection
